import { Knex } from "knex";
import { v4 as uuidv4 } from "uuid";

function getRandomSize(min: number, max: number): number {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

export async function seed(knex: Knex): Promise<void> {
    await knex("files").del();

    await knex("files").insert([
        // John Doe
        { id: 1, name: "Sotcks1", path: "home-Finance-Investments-Stocks", extension: "docx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 2, name: "Sotcks2", path: "home-Finance-Investments-Stocks", extension: "docx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 3, name: "Sotcks3", path: "home-Finance-Investments-Stocks", extension: "docx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 4, name: "Sotcks4", path: "home-Finance-Investments-Stocks", extension: "docx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 5, name: "Summary", path: "home-Finance-Investments-Stocks", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 6, name: "Found1", path: "home-Finance-Investments-Mutual Founds", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 7, name: "Found2", path: "home-Finance-Investments-Mutual Founds", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 8, name: "Found3", path: "home-Finance-Investments-Mutual Founds", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 9, name: "Found4", path: "home-Finance-Investments-Mutual Founds", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 10, name: "Summary", path: "home-Finance-Investments-Mutual Founds", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 11, name: "Retirement1", path: "home-Finance-Retirement", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 12, name: "Retirement2", path: "home-Finance-Retirement", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 13, name: "Retirement3", path: "home-Finance-Retirement", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 14, name: "Summary", path: "home-Finance-Retirement", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 15, name: "Insurance1", path: "home-Finance-Insurance", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 16, name: "Insurance2", path: "home-Finance-Insurance", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 17, name: "Insurance3", path: "home-Finance-Insurance", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 18, name: "Insurance4", path: "home-Finance-Insurance", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 19, name: "Summary", path: "home-Finance-Insurance", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 20, name: "Summary", path: "home-Finance", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 21, name: "Exercise1", path: "home-Gym", extension: "mp4", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 22, name: "Exercise2", path: "home-Gym", extension: "mp4", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 23, name: "Exercise3", path: "home-Gym", extension: "mp4", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 24, name: "Exercise4", path: "home-Gym", extension: "mp4", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 25, name: "Exercise5", path: "home-Gym", extension: "mp4", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 26, name: "Planning", path: "home-Work-Project 1", extension: "docx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 27, name: "Spreadsheet", path: "home-Work-Project 1", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 28, name: "Planning", path: "home-Work-Project 2", extension: "docx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 29, name: "Spreadsheet", path: "home-Work-Project 2", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 30, name: "Planning", path: "home-Work-Project 3", extension: "docx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 31, name: "Spreadsheet", path: "home-Work-Project 3", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 32, name: "RG", path: "home-Docs", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 33, name: "CFP", path: "home-Docs", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 34, name: "Passport", path: "home-Docs", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 35, name: "scheadule", path: "home-Home-Vacation-Rome", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 36, name: "Restaurants", path: "home-Home-Vacation-Rome", extension: "docx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 37, name: "Sights", path: "home-Home-Vacation-Rome", extension: "dpcx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 38, name: "Costs", path: "home-Home-Vacation-Rome", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 39, name: "scheadule", path: "home-Home-Vacation-USA", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 40, name: "Restaurants", path: "home-Home-Vacation-USA", extension: "docx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 41, name: "Sights", path: "home-Home-Vacation-USA", extension: "dpcx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 42, name: "Costs", path: "home-Home-Vacation-USA", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 43, name: "scheadule", path: "home-Home-Vacation-New Zealand", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 44, name: "Restaurants", path: "home-Home-Vacation-New Zealand", extension: "docx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 45, name: "Sights", path: "home-Home-Vacation-New Zealand", extension: "dpcx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 46, name: "Costs", path: "home-Home-Vacation-New Zealand", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 47, name: "scheadule", path: "home-Home-Vacation-Scotland", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 48, name: "Restaurants", path: "home-Home-Vacation-Scotland", extension: "docx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 49, name: "Sights", path: "home-Home-Vacation-Scotland", extension: "dpcx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 50, name: "Costs", path: "home-Home-Vacation-Scotland", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 51, name: "Purchase1", path: "home-Home-Purchases", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 52, name: "Purchase2", path: "home-Home-Purchases", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 53, name: "Purchase3", path: "home-Home-Purchases", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "1" },
        { id: 54, name: "Purchase4", path: "home-Home-Purchases", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "1" },

        // // Jane Doe
        { id: 55, name: "Planning", path: "home-Work-Project 1", extension: "docx", size: getRandomSize(1024, 4096), user_id: "2" },
        { id: 56, name: "Spreadsheet", path: "home-Work-Project 1", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "2" },
        { id: 57, name: "Planning", path: "home-Work-Project 2", extension: "docx", size: getRandomSize(1024, 4096), user_id: "2" },
        { id: 58, name: "Spreadsheet", path: "home-Work-Project 2", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "2" },
        { id: 59, name: "Planning", path: "home-Work-Project 3", extension: "docx", size: getRandomSize(1024, 4096), user_id: "2" },
        { id: 60, name: "Spreadsheet", path: "home-Work-Project 3", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "2" },
        { id: 61, name: "Apreseantation", path: "home-Work", extension: "pptx", size: getRandomSize(1024, 4096), user_id: "2" },
        { id: 62, name: "Schedule", path: "home-Home", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "2" },
        { id: 63, name: "Schedule", path: "home-Home-Children-School", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "2" },
        { id: 64, name: "Doc1", path: "home-Home-Children-School", extension: "docx", size: getRandomSize(1024, 4096), user_id: "2" },
        { id: 65, name: "Doc2", path: "home-Home-Children-School", extension: "docx", size: getRandomSize(1024, 4096), user_id: "2" },
        { id: 66, name: "Schedule", path: "home-Home-Children-Medical Care", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "2" },
        { id: 67, name: "Doc1", path: "home-Home-Children-Medical Care", extension: "docx", size: getRandomSize(1024, 4096), user_id: "2" },
        { id: 68, name: "photo1", path: "home-Photos", extension: "jpg", size: getRandomSize(1024, 4096), user_id: "2" },
        { id: 69, name: "photo2", path: "home-Photos", extension: "jpg", size: getRandomSize(1024, 4096), user_id: "2" },
        { id: 70, name: "photo3", path: "home-Photos", extension: "jpg", size: getRandomSize(1024, 4096), user_id: "2" },
        { id: 71, name: "photo4", path: "home-Photos", extension: "jpg", size: getRandomSize(1024, 4096), user_id: "2" },
        { id: 72, name: "photo5", path: "home-Photos", extension: "jpg", size: getRandomSize(1024, 4096), user_id: "2" },
        { id: 73, name: "photo6", path: "home-Photos", extension: "jpg", size: getRandomSize(1024, 4096), user_id: "2" },
        { id: 74, name: "photo7", path: "home-Photos", extension: "jpg", size: getRandomSize(1024, 4096), user_id: "2" },
        { id: 75, name: "photo8", path: "home-Photos", extension: "jpg", size: getRandomSize(1024, 4096), user_id: "2" },
        { id: 76, name: "photo9", path: "home-Photos", extension: "jpg", size: getRandomSize(1024, 4096), user_id: "2" },


        // // Emily Smith
        { id: 77, name: "Schedule", path: "home-School-Pre School", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 78, name: "subject1", path: "home-School-Pre School", extension: "docx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 79, name: "subject2", path: "home-School-Pre School", extension: "docx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 80, name: "subject3", path: "home-School-Pre School", extension: "docx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 81, name: "subject4", path: "home-School-Pre School", extension: "docx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 82, name: "Schedule", path: "home-School-Elementary", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 83, name: "subject1", path: "home-School-Elementary", extension: "docx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 84, name: "subject2", path: "home-School-Elementary", extension: "docx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 85, name: "subject3", path: "home-School-Elementary", extension: "docx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 86, name: "subject4", path: "home-School-Elementary", extension: "docx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 87, name: "Schedule", path: "home-School-Junior High", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 88, name: "subject1", path: "home-School-Junior High", extension: "docx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 89, name: "subject2", path: "home-School-Junior High", extension: "docx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 90, name: "subject3", path: "home-School-Junior High", extension: "docx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 91, name: "subject4", path: "home-School-Junior High", extension: "docx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 92, name: "Schedule", path: "home-School-High School", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 93, name: "subject1", path: "home-School-High School", extension: "docx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 94, name: "subject2", path: "home-School-High School", extension: "docx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 95, name: "subject3", path: "home-School-High School", extension: "docx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 96, name: "subject4", path: "home-School-High School", extension: "docx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 97, name: "Schedule", path: "home-School-Collage", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 98, name: "subject1", path: "home-School-Collage", extension: "docx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 99, name: "subject2", path: "home-School-Collage", extension: "docx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 100, name: "subject3", path: "home-School-Collage", extension: "docx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 101, name: "subject4", path: "home-School-Collage", extension: "docx", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 102, name: "show1", path: "home-Shows", extension: "mp4", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 103, name: "show2", path: "home-Shows", extension: "mp4", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 104, name: "show3", path: "home-Shows", extension: "mp4", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 105, name: "show4", path: "home-Shows", extension: "mp4", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 106, name: "movie1", path: "home-Movies", extension: "mp4", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 107, name: "movie2", path: "home-Movies", extension: "mp4", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 108, name: "movie3", path: "home-Movies", extension: "mp4", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 109, name: "movie4", path: "home-Movies", extension: "mp4", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 110, name: "song1", path: "home-Musics", extension: "mp3", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 111, name: "song2", path: "home-Musics", extension: "mp3", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 112, name: "song3", path: "home-Musics", extension: "mp3", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 113, name: "song4", path: "home-Musics", extension: "mp3", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 114, name: "song5", path: "home-Musics", extension: "mp3", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 115, name: "song6", path: "home-Musics", extension: "mp3", size: getRandomSize(1024, 4096), user_id: "3" },
        { id: 116, name: "song7", path: "home-Musics", extension: "mp3", size: getRandomSize(1024, 4096), user_id: "3" },

        // // Michael Johnson
        { id: 117, name: "Savings1", path: "home-Personal Finance-Savings", extension: "docx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 118, name: "Savings1", path: "home-Personal Finance-Savings", extension: "docx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 119, name: "summary", path: "home-Personal Finance-Savings", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 120, name: "Rent", path: "home-Personal Finance-Expenses", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 121, name: "Utilities", path: "home-Personal Finance-Expenses", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 122, name: "Groceries", path: "home-Personal Finance-Expenses", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 123, name: "summary", path: "home-Personal Finance-Expenses", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 124, name: "Stock1", path: "home-Personal Finance-Investments-Stocks", extension: "docx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 125, name: "Stock1", path: "home-Personal Finance-Investments-Stocks", extension: "docx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 126, name: "summary", path: "home-Personal Finance-Investments-Stocks", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 127, name: "Property1", path: "home-Personal Finance-Investments-Real Estate", extension: "docx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 128, name: "Property2", path: "home-Personal Finance-Investments-Real Estate", extension: "docx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 129, name: "summary", path: "home-Personal Finance-Investments-Real Estate", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 130, name: "Policy1", path: "home-Personal Finance-Insurance-Health", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 131, name: "Policy2", path: "home-Personal Finance-Insurance-Health", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 132, name: "summary", path: "home-Personal Finance-Insurance-Health", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 133, name: "Policy1", path: "home-Personal Finance-Insurance-Auto", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 134, name: "Policy2", path: "home-Personal Finance-Insurance-Auto", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 135, name: "summary", path: "home-Personal Finance-Insurance-Auto", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 136, name: "Camara Gear", path: "home-Hobbies-Photography", extension: "docx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 137, name: "photo1", path: "home-Hobbies-Photography-Photos", extension: "jpg", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 138, name: "photo2", path: "home-Hobbies-Photography-Photos", extension: "jpg", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 139, name: "photo3", path: "home-Hobbies-Photography-Photos", extension: "jpg", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 140, name: "photo4", path: "home-Hobbies-Photography-Photos", extension: "jpg", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 141, name: "Planting Schedule", path: "home-Hobbies-Gardening", extension: "docx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 142, name: "Flower1", path: "home-Hobbies-Gardening-Plants", extension: "jpg", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 143, name: "Flower2", path: "home-Hobbies-Gardening-Plants", extension: "jpg", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 144, name: "Vegetable1", path: "home-Hobbies-Gardening-Plants", extension: "jpg", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 145, name: "Vegetable2", path: "home-Hobbies-Gardening-Plants", extension: "jpg", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 146, name: "Proposal", path: "home-Work-Projects-Project 1", extension: "docx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 147, name: "Timeline", path: "home-Work-Projects-Project 1", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 148, name: "Proposal", path: "home-Work-Projects-Project 2", extension: "docx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 149, name: "Timeline", path: "home-Work-Projects-Project 2", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 150, name: "Proposal", path: "home-Work-Projects-Project 3", extension: "docx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 151, name: "Timeline", path: "home-Work-Projects-Project 3", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 152, name: "Meeting1", path: "home-Work-Meetings", extension: "docx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 153, name: "Meeting2", path: "home-Work-Meetings", extension: "docx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 154, name: "Meeting3", path: "home-Work-Meetings", extension: "docx", size: getRandomSize(1024, 4096), user_id: "4" },
        { id: 155, name: "Meeting4", path: "home-Work-Meetings", extension: "docx", size: getRandomSize(1024, 4096), user_id: "4" },

        // // Samantha Davis
        { id: 156, name: "Module1", path: "home-Personal Development-Courses-Course 1-Materials", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 157, name: "Module2", path: "home-Personal Development-Courses-Course 1-Materials", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 158, name: "Module3", path: "home-Personal Development-Courses-Course 1-Materials", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 159, name: "Assignment1", path: "home-Personal Development-Courses-Course 1-Assignments", extension: "docx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 160, name: "Assignment2", path: "home-Personal Development-Courses-Course 1-Assignments", extension: "docx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 161, name: "Assignment3", path: "home-Personal Development-Courses-Course 1-Assignments", extension: "docx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 162, name: "Reading List", path: "home-Personal Development-Books", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 163, name: "Book1", path: "home-Personal Development-Books", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 164, name: "Book2", path: "home-Personal Development-Books", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 165, name: "Book3", path: "home-Personal Development-Books", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 166, name: "Book4", path: "home-Personal Development-Books", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 167, name: "Plan1", path: "home-Fitness-Work Plans", extension: "docx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 168, name: "Plan2", path: "home-Fitness-Work Plans", extension: "docx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 169, name: "Plan3", path: "home-Fitness-Work Plans", extension: "docx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 170, name: "Plan4", path: "home-Fitness-Work Plans", extension: "docx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 171, name: "Meal Plan", path: "home-Fitness-Nutrition", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 172, name: "Recepie1", path: "home-Fitness-Nutrition-Recipies", extension: "docx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 173, name: "Recepie1", path: "home-Fitness-Nutrition-Recipies", extension: "docx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 174, name: "Bucket List", path: "home-Travel", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 175, name: "Itinerary", path: "home-Travel-Past Trips-Trip 1", extension: "docx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 176, name: "Expenses", path: "home-Travel-Past Trips-Trip 1", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 177, name: "Itinerary", path: "home-Travel-Past Trips-Trip 2", extension: "docx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 178, name: "Expenses", path: "home-Travel-Past Trips-Trip 2", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 179, name: "Destination1", path: "home-Travel-Future Plans", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 180, name: "Destination2", path: "home-Travel-Future Plans", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 181, name: "Destination3", path: "home-Travel-Future Plans", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 182, name: "Post1", path: "home-Blog-Drafts", extension: "docx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 183, name: "Post2", path: "home-Blog-Drafts", extension: "docx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 184, name: "Post3", path: "home-Blog-Drafts", extension: "docx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 185, name: "Image1", path: "home-Blog-Images", extension: "jpg", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 186, name: "Image2", path: "home-Blog-Images", extension: "jpg", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 187, name: "Image3", path: "home-Blog-Images", extension: "jpg", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 188, name: "Budget", path: "home-Finance", extension: "xlsx", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 189, name: "Statement1", path: "home-Finance-Bank Statement", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 190, name: "Statement2", path: "home-Finance-Bank Statement", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "5" },
        { id: 191, name: "Statement3", path: "home-Finance-Bank Statement", extension: "pdf", size: getRandomSize(1024, 4096), user_id: "5" },

    ]);
}
